---
- name: parser meta data
  parser_metadata:
    version: 1.0
    command: show running-config
    network_os: ios

- name: match hostname
  pattern_match:
    regex: "!\\nhostname ([^\\n]+)"
  register: ios_hostname
  export: yes

- name: match version
  pattern_match:
    regex: "^version (\\S+)"
  register: ios_major_version
  export: yes

- name: match named standard ACL
  pattern_match:
    regex: "ip access-list standard ([^!]+)"
  register: ios_standard_named_acl
  export: yes

- name: match named extended ACL
  pattern_match:
    regex: "ip access-list extended([^!]+)"
  register: ios_extended_named_acl
  export: yes

- name: match numbered standard ACL
  pattern_match:
    regex: "\\naccess-list (\\d+) ([^\\n]+)"
    match_all: yes
  register: ios_numbered_acl
  export: yes

#### SNMP ####

- name: match sections
  pattern_match:
    regex: "snmp-server community (\\S+) (RO|RW)"
    match_all: yes
  register: ios_snmp_community
  export: yes

### line ####
- name: capture line 0 subsection
  pattern_match:
    regex: "(^line [^!]+\n!)" #    regex: "\\\ninterface ([^\\\n]+)([^!]+)"
    match_all: yes
  register: line_subset
  export: yes


#### AAA ####
- name: capture aaa global config
  pattern_match:
    regex: "^aaa (?!group)[^\\n]+" #    regex: "\\\ninterface ([^\\\n]+)([^!]+)"
    match_all: yes
  register: ios_aaa_global
  export: no

- name: capture radius-server global config
  pattern_match:
    regex: "^(radius-server [^\\n]+)" #    regex: "\\\ninterface ([^\\\n]+)([^!]+)"
    match_all: yes
  register: ios_radiusserver_global
  export: no

- name: capture ip radius global config
  pattern_match:
    regex: "^(ip radius [^\\n]+)" #    regex: "\\\ninterface ([^\\\n]+)([^!]+)"
    match_all: yes
  register: ios_ipradius
  export: yes

- name: capture ip tacacs global config
  pattern_match:
    regex: "^(ip tacacs [^\\n]+)" #    regex: "\\\ninterface ([^\\\n]+)([^!]+)"
    match_all: yes
  register: ios_iptacacs
  export: no

- name: capture aaa group server subsection
  pattern_match:
    regex: "(^aaa group server [^!]+\n!)" #    regex: "\\\ninterface ([^\\\n]+)([^!]+)"
    match_all: yes
  register: ios_aaa_group_subset
  export: no

- name: match aaa group
  pattern_group:
    - name: match name
      pattern_match:
        regex: "(?:aaa group server tacacs\\+ |aaa group server radius )([^\\\n]+)"
        content: "{{ item.matches  }}"
      register: name

    - name: match config
      pattern_match:
        regex: "(?:aaa group server tacacs\\+ |aaa group server radius )(?:\\S+)([^!]+)"
        content: "{{ item.matches  }}"
      register: config

    - name: match servers
      pattern_match:
        regex: "server-private ([^\n]+)"
        content: "{{ item.matches  }}"
        match_all: yes
      register: servers

  loop: "{{ ios_aaa_group_subset }}"
  register: ios_aaa_groups
  export: yes
