---
# tasks file for cisco_config_parser
- name: run enable level commands
  ios_command:
    authorize: yes
    commands:
      - show run
  register: print_output

- name: save output to a file
  copy: content="{{ print_output.stdout[0] }}" dest="{{role_path}}/files/{{ inventory_hostname }}.ios"

- debug:
    msg: "{{lookup('file','{{role_path}}/files/{{ inventory_hostname }}.ios')}}"

- name: Generate vars with parser
  command_parser:
    file: "templates/parser/parse_running_config.yml"
    content: "{{lookup('file','{{role_path}}/files/{{ inventory_hostname }}.ios')}}"

- name: Generate host_vars from templates
  template:
    src: templates/ios_host_vars_template.j2
    dest: "host_vars/{{ inventory_hostname }}"
