---
- name: parser meta data
  parser_metadata:
    version: 1.0
    command: show running_configuration
    network_os: ios

- name: capture all access-list subsection fully in oxidized show running_configuration
  pattern_match:
    #regex: ip access-list standard (.*) :#(ip access-list standard [^!]+)(?=\\nip access-list|\\n!) #regex: "\\\n(ip access-list standard [^!]+)"
    regex:  "ip access-list (\\w+) (\\S+)\\n ([^!]+)"
    match_all: yes
  register: ansible_net_ACL
  export: yes
