---
- name: parser meta data
  parser_metadata:
    version: 1.0
    command: show running_configuration
    network_os: ios

###########################
### Capture subsection ####
- name: capture line 0 subsection
  pattern_match:
    regex: "(^line [^!]+\n!)" #    regex: "\\\ninterface ([^\\\n]+)([^!]+)"
    match_all: yes
  register: line_subset
  export: yes

###########################
### shrink line        ####
- name: match line
  pattern_group:
    - name: match line type
      pattern_match:
        regex: "line ([^\\\n]+)"
        content: "{{ item.matches  }}"
      register: type

    - name: match full config
      pattern_match:
        regex: "(?:line [^\\\n]+\\\n)([^!]+)"
        content: "{{ item.matches  }}"
      register: config

  loop: "{{ line_subset }}"
  register: lines
  export: yes
